CREATE TABLE STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE) VALUES
 ('1','RAM','DELHI','*****',18),
 ('2','RAMESH','GURGAON','*****',18),
 ('3','SWIT','ROHTAK','*****',20),
 ('4','SURESH','DELHI','*****',18),
 ('5','AMAN','ROHTAK','*****',20),
 ('6','HARSH','GURGAON','*****',18);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS ='DELHI';
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME ='RAM';
SELECT * FROM STUDENT WHERE AGE = 18 OR NAME ='SWIT';
SELECT * FROM STUDENT WHERE NAME = 18 OR AGE = 20;